### ISSUE TITLE
Siren Platform Demo Data 10.0.2 Post Build Manual Ui Tests

### ISSUE THREAD

**Issue by colmose** [colmose/pb_test#538]
> Keep the console open while performing these checks and ensure there are no unusual errors in the console.

#### TODO:
* Do we download the investment demo or ssh tunnel to it?

- [ ] Download `siren-platform-no-data-no-security-X.X.X.zip` and unzip
- [ ] Connect to investment demo elasticsearch...
  * Run `ssh -L 9220:127.0.0.1:15041 investment.qa.siren.io -f -N ` in a terminal to connect to the investment QA elasticsearch instance on localhost:9220
- [ ] Run Siren Investigate...

### Initial checks:
- [ ] Expand all menus (e.g Companies, Investment Rounds, Investors, Graph Browser...)
- [ ] Check if all dashboards load (e.g all articles, all companies, Graph Browser)
- [ ] Check if the counts on dashboards and relational buttons are completed

### Datasource checks:
- [ ] Open the "Datasource page" on the Management menu and check if the `Rest Datasources Types` are loaded

### Index and Relations checks:
**Check existing relations**
  - [ ] Open the "Index and Relations page" on the Management menu and select the index pattern `Article`
  - [ ] Check if all the tabs load correctly
  - [ ] Check on the `fields` tab if there is a join icon (<->) on the companies field
  - [ ] Check on the `relations` tab if there is a relation between article <-> company
  - [ ] Check on the `Graph View` tab if the relations are correct

**Creating new relations**
  - [ ] On the `relations` tab click on `Add Relation +`
  - [ ] Select `Company` index pattern and `City` field for Left Relation
  - [ ] Select `Investor` index pattern and `City` field for Right Relation
  - [ ] Scroll up and show the new `company.city—investor.city` line created between Company and Investor
  - [ ] Scroll down and delete the new relationship just created

### Workflow filtering checks:

**Dashboards**
  - [ ] Check if the `Switch to standard template` in the "Articles Table widget" works fine
  - [ ] Perform a full-text search with the words "big data" and check if these words are highlighted in "Article Table widget"
  - [ ] Check if the "Articles Wordcloud widget" was correctly updated with this search
  - [ ] Click on the relational button `Companies` and it should navigate to the companies dashboard
  - [ ] Check the filter created and it should show  all the companies related to those articles that mention the words "big data"
  - [ ] In the "Map of Companies widget", click on the `black square icon` and filter selecting the United States area
  - [ ] All the counts on dashboards and relational buttons should be updated
  - [ ] Click on `Investments rounds` relational button and it should navigate to the Investments dashboard
  - [ ] Check the filter created and it should the set of investments made in companies that were mentioned in articles that spoke about big data
  - [ ] On the "Investment Round widget" select the` Round A slice`
  - [ ] Click on the `Investors` relational button

**Graph Browser**
  - [ ] Click on `Graph Browser` in sidebar to open the graph browser
  - [ ]  Click on `+Add` and select "Investors", "Investments", and "All Companies" nodes
  - [ ]  Click on `Standard button` to rearrange the nodes on the graph
  - [ ] Select the left side of the nodes and click on the `crop button`
  - [ ]  Right click and `Expand by Relation`, select "Has Competitor" and rearrange the nodes
  - [ ]  Right click and `Expand by Relation`, select "Mentioned" and rearrange the nodes
  - [ ] Click on `Toggle map mode` to show the nodes on the map
  - [ ] Click on `Toggle timeline mode` to see the nodes over a timeline
  - [ ] Adjust beginning and end of the timeline to cover the peak actvity
  - [ ] Click on `<->` at bottom of timeline and click on `Play button`

**Graph Browser Live filter**
  - [ ] Remove all filters
  - [ ] Select some nodes on the graph that you want for the live filter
  - [ ] Click on `Live Filter`
  - [ ] Click on `Unlink Live Filter`
  - [ ] Click on `Pin filter`
  - [ ] Go back to the dashboard and it should update the dashboard with the selected document nodes
